const data ={
    products:[
        {
            _id: '1',
            name: 'Brown Nike',
            category: 'Sneakers',
            size:'9',
            image: '/images/brownnike.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }, {
            _id: '2',
            name: 'Brown Vans',
            category: 'Sneakers',
            size: '8',
            image: '/images/brownvans.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }, {
            _id: '3',
            name: 'Red Nikes',
            category: 'Sneakers',
            size:'9',
            image: '/images/rednikes.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }, {
            _id: '4',
            name: 'Uptowns',
            category: 'Sneakers',
            size: '11',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }, {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }, {
            _id: '5',
            name: 'White and Blue air force One',
            category: 'Sneakers',
            size:'9.5',
            image: '/images/whaitandblueips.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '6',
            name: 'Yellow Nikes',
            category: 'Sneakers',
            size:'10.5',
            image: '/images/yellownike.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          }
        

]}

export default data;